services:
  - type: web
    name: carpooling-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /
    autoDeploy: true 