services:
  - type: web
    name: carpool-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://carpool-app-1.onrender.com
    autoDeploy: true 